"""empty message

Revision ID: 70b993b3a21b
Revises: 8e4424797cf4
Create Date: 2023-06-17 01:12:44.437906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b993b3a21b'
down_revision = '8e4424797cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_comments', sa.String(length=80), nullable=False))
        batch_op.drop_column('aditional_coments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditional_coments', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('aditional_comments')

    # ### end Alembic commands ###
